### ISSUE TITLE
GitBook moved to new summerinthecity GitBook organization

### ISSUE THREAD

**Issue by nielsdrost** [summerinthecity/report#1]
Due to a new (more logical) setup for GitBook there is now a one-to-one relationship between GitBook and GitHub organizations.

Thus, the summerinthecity book is now moved to a new summerinthecity GitBook organization.

We should update all links to https://summerinthecity.gitbooks.io/summerinthecity/content/ instead of the old https://nlesc.gitbooks.io/summerinthecity/content/

**Comment by jiskattema** [comment]
Links in this repo appear to be ok.
Links in the other repos in this organization ok (there are none).
